### ISSUE TITLE
Add support of SVG for comparison

### ISSUE THREAD

**Issue by Winner95** [rsmbl/Resemble.js#141]
I think it might be a useful feature regarding a lot of tools for auto optimisation of SVG (plugins as SVGO, which works also with gulp/webpack) and sometimes it is very convenient to have option to compare a lot of icons automatically too.

**Comment by jamescryer** [comment]
I'm reviewing open issues, apologies for the very late reply.  SVG is supported, unless there is a particular use-case that doesn't work? Feel free to reopen or add more info.
