### ISSUE TITLE
Not running in docker/alpine3.7

### ISSUE THREAD

**Issue by hcomnetworkers** [rsmbl/Resemble.js#145]
With your current dependency to canvas-prebuilt 1.6, resemblejs does not run under docker, e.g. alpine 3.7.

Canvas-prebuilt requires a shared library libpng12, which is not available in alpine 3.7 or Debian 9. The newer installable version is libpng16.

Could you update your dependency on canvas-prebuilt? I think they have fixed their libpng-dependency in version 2.

**Comment by wswebcreation** [comment]
@jamescryer 
I think this can be closed because you're now not using `canvas-prebuilt` anymore
