### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by khrome83** [rsmbl/Resemble.js#147]
I ran into a issue where the version of node-prebuilt does not work in a Lambda. I forked the repo and ran `npm install`. I then ran `npm run test`.

Before making any change, the tests fail. I included screenshots of my node/npm versions and my failing test. I will file a different issue for the problem with Lambda usage.

<img width="557" alt="screen shot 2018-07-25 at 6 10 33 am" src="https://user-images.githubusercontent.com/1844739/43197666-79a5fd4c-8fd1-11e8-9123-705c9cd665d0.png">
<img width="722" alt="screen shot 2018-07-25 at 6 10 12 am" src="https://user-images.githubusercontent.com/1844739/43197667-79dd7f56-8fd1-11e8-9f2b-42a7cc32bb4b.png">

**Comment by jamescryer** [comment]
Do you have the same issue with the latest version of Resemble.js?
