### ISSUE TITLE
resemble.js fails in Lambda

### ISSUE THREAD

**Issue by khrome83** [rsmbl/Resemble.js#148]
When I deploy this in a lambda function, i get the following error - 

<img width="1002" alt="screen shot 2018-07-25 at 6 13 00 am" src="https://user-images.githubusercontent.com/1844739/43197774-d2b6531e-8fd1-11e8-902b-2f144c37891c.png">

After some research, i believe it is because of the `canvas-prebuilt` not working correctly in version `8.10` of node on AWS Lamda. 

I have forked the repo and am attempting to use [canvas-aws-prebuilt](https://github.com/dankochetov/canvas-aws-prebuilt).

But I am blocked by #147.

**Comment by khrome83** [comment]
`canvas-aws-prebuilt` does not seem to work either. It was more outdated than I realized.

**Comment by dcharbonnier** [comment]
#156 can probably help

**Comment by jamescryer** [comment]
Does the latest version work?

**Comment by slixin** [comment]
May I ask if the issue has been fixed? Is there a workaround to let resemble.js working on AWS Lambda?

**Comment by nrathi** [comment]
Could anyone help me with running Resemble on AWS Lambda? 

Resemble is currently using canvas@2.11. I've been trying combinations of Nod 16/16, ARM vs. x86 architecture, hitting a bunch of dead ends.
