### ISSUE TITLE
canvas-prebuild deprecated

### ISSUE THREAD

**Issue by dcharbonnier** [rsmbl/Resemble.js#156]
NOTE: the canvas-prebuilt package is deprecated. As of version 2, canvas itself bundles prebuilt versions from this repo. Install by running

npm install --save canvas
…and use canvas as usual.

**Comment by jamescryer** [comment]
I've been looking into this but it appears that the prebuilt packages for Canvas for Windows 10 on Node 10 & 11 cause the following error, at least for me 

```
    TypeError: Cannot read property 'call' of undefined
      at setSource (node_modules/canvas/lib/image.js:102:14)
      at Image.set (node_modules/canvas/lib/image.js:68:7)
      at loadImageData (resemble.js:270:33)
```

Struggling to find the time to understand the issue, seems to relate to https://github.com/Automattic/node-canvas/issues/1294
https://github.com/Automattic/node-canvas/pull/1247

**Comment by jamescryer** [comment]
I've just pushed a v3 branch https://github.com/HuddleEng/Resemble.js/tree/v3.  Unfortunately it doesn't work on Ubuntu (Docker Node:11 image), and intermittently breaks on Windows 10 - not ready for general release.

**Comment by chrisguttandin** [comment]
Thanks for the update. Is there anything I could do to help you? Or do you think it is just a matter of waiting for node-canvas to stabilize on Node v11?
