### ISSUE TITLE
These images are the same! message is shown but images aren't equal

### ISSUE THREAD

**Issue by bondom** [rsmbl/Resemble.js#162]
Screenshot below is from your demo page([http://rsmbl.github.io/Resemble.js/](http://rsmbl.github.io/Resemble.js/)). Images aren't equal, but `These images are the same!` message is shown. 
Maybe I miss something and your library works only in some particular cases.

![image](https://user-images.githubusercontent.com/18090218/50680892-12a88300-1012-11e9-800b-ecc2d9aa3af0.png)

Please say why difference isn't shown.

**Comment by jamescryer** [comment]
Thanks for taking the time to raise this issue, unfortunately I can't reproduce the bug.  Do you see any errors logged in console? Do other image comparisons work?

**Comment by bondom** [comment]
Now it works...
