### ISSUE TITLE
Unable to run sample code provide on Github main page.

### ISSUE THREAD

**Issue by Sumit-Soman** [rsmbl/Resemble.js#169]
const compareImages = require("resemblejs/compareImages");
const fs = require("mz/fs");

async function getDiff() {
    const options = {
        output: {
            errorColor: {
                red: 255,
                green: 0,
                blue: 255
            },
            errorType: "movement",
            transparency: 0.3,
            largeImageThreshold: 1200,
            useCrossOrigin: false,
            outputDiff: true
        },
        scaleToSameSize: true,
        ignore: "antialiasing"
    };

    // The parameters can be Node Buffers
    // data is the same as usual with an additional getBuffer() function
    const data = await compareImages(
        await fs.readFile("./demoassets/People.jpg"),
        await fs.readFile("./demoassets/People2.jpg"),
        options
    );

    await fs.writeFile("./output.png", data.getBuffer());
}

getDiff();

Used the above code, using my local images. code existed with no error. 
On debugging control exist from compareImages method.
i am using png images do we need to use jpg only

**Comment by jamescryer** [comment]
It should work with a variety of image types.. I'm unable to investigate right now.  Can you try using an earlier version of Resemble.js to see if that works?

**Comment by Sumit-Soman** [comment]
Thanks for the prompt replay.
Downgraded to v2.10.3. Comparison is working fine. Same code

**Comment by jamescryer** [comment]
Unfortunately I am unable to reproduce the issue, the code above works for me with both PNG and JPG.  I'll leave the ticket open for now

**Comment by Sumit-Soman** [comment]
Hi James,

Issue was not with images type. 

Latest version was not working producing the diff image. I was able to produce diff with lower version.
Downgraded to v2.10.3.

**Comment by jamescryer** [comment]
I could not reproduce the issue with ^3.0.0 on Node v10.13.0.  It produced an image diff for me.  What version of Node are you using?

**Comment by Sumit-Soman** [comment]
Node: v8.11.1. Probably this could be the issue

**Comment by jamescryer** [comment]
Had another attempt with v8, but I am still unable to reproduce any issue, it works for me. I wonder if there is something about your images. Please let us know if you discover what the problem is.  I'll leave the ticket open for now.
