### ISSUE TITLE
Update canvas dependency to support node v12

### ISSUE THREAD

**Issue by sasensi** [rsmbl/Resemble.js#176]
Hi,

Could you update your `canvas` dependency to version `2.5.0` ?
As reported in https://github.com/Automattic/node-canvas/issues/1410, the version that you are using (`2.2.0`) is not compatible with node v12 which is the current stable version of node.
https://github.com/paperjs/paper.js CI relies on your library and this would be a great thing for us.

Thank you.

**Comment by jamescryer** [comment]
Relates to https://github.com/rsmbl/Resemble.js/pull/173

**Comment by jamescryer** [comment]
Sorry for the delay, the Node-Canvas prebuilds are now available and I've upgraded to 2.6.0. This is now resolved as of Resemble v3.2.0.

**Comment by sasensi** [comment]
Thank you
