### ISSUE TITLE
Can the 2 images have different colors in output

### ISSUE THREAD

**Issue by abhagupta** [rsmbl/Resemble.js#186]
If my output settings are 
```
{
  errorColor: {
    red: 57,
    green: 255,
    blue: 20
  },
  errorType: 'movement',
  largeImageThreshold: 1200,
  useCrossOrigin: false,
  outputDiff: true
}
```
the images compared are both in neon colors.. Can I set of the baseline image to be a totally different color so its easy to differentiate what has changed in the newer image?

**Comment by jamescryer** [comment]
There is no way currently to change the colour completely.  The following might help?
```
  outputSettings({
    transparency: 0.3
  });
```
