### ISSUE TITLE
Resemble and cross-origin data

### ISSUE THREAD

**Issue by ccoffey** [rsmbl/Resemble.js#19]
I was wondering if its possible to use Resemble with remote images? Basically I am trying to do the following but I am getting a SecurityError.

Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

Is there anyway of getting around this?

var img1 = 'http://www.google.com/think/images/google-trends_tools_sm.jpg';
var img2 = 'http://informationng.com/wp-content/uploads/2014/02/google.jpg';
resemble(img1).compareTo(img2).onComplete(function(data){
    console.log(data);
});

Is it possible to do something like the following?

var img1 = Image()
img1.src = 'http://www.google.com/think/images/google-trends_tools_sm.jpg';

var img2 = Image();
img2.src = 'http://informationng.com/wp-content/uploads/2014/02/google.jpg';

resemble(img1).compareTo(img2).onComplete(function(data){
    console.log(data);
});

I'm not sure why its okay to load a remote image like this <img src='http://www.google.com/think/images/google-trends_tools_sm.jpg'></img> but its not okay to load it using Javascript.

**Comment by denizkutluay** [comment]
I am having the same issue as ccoffey. I tried using links from online files, local files, dropbox files and even the People.jpg files in this repository. None of them worked :(

My lines are the same as above:

function CompareLinks(){
  
  var strin1 = 'https://dl.dropboxusercontent.com/u/14676645/LinkInfo/linkL6a1%7B0%7D.png';

  var strin2 = 'https://dl.dropboxusercontent.com/u/14676645/LinkInfo/linkL6a1%7B1%7D.png';

  var obj = resemble(strin1).compareTo(strin2).onComplete(function(data){
  console.log(data);
  });

  var str = JSON.stringify(obj, null, 4);
  console.log(str);
  alert(str);
}

and the html file:

<!DOCTYPE html>
<head>
	<script src="C:\Users\Deniz\Desktop\Resemble.js-master\resemble.js"></script>
	<script src="C:\Users\Deniz\Desktop\Resemble.js-master\LinkInfo\CompareLinks.js"></script>
</head>

<body>
	<input type="button" onclick="CompareLinks()" value="Click"/>
</body>
</html>

------------------------------------------
What am I missing?

Thank you.

**Comment by denizkutluay** [comment]
This was the original fix: #70
