### ISSUE TITLE
Storing image fingerprints for comparing later

### ISSUE THREAD

**Issue by Ravenglass** [rsmbl/Resemble.js#203]
Hi, I have a case where I have to find similar images based a given image. The library consists of over 20,000 images.

Is there a way to analyze each image and store just the fingerprint data in a DB and then compare them really quickly to find similar results?

One method I thought of was to resize each image to just 10x10 pixels and store that and then compare the downscaled version of the selected image against all 20K images.

Is this something that can be achieved, or am I completely off the mark here? Thanx...

**Comment by jamescryer** [comment]
Sounds like this would be prone to error, and lacking the fidelity needed.  But technically implementable.
