### ISSUE TITLE
Comparing two different images seems to fail

### ISSUE THREAD

**Issue by thathurtabit** [rsmbl/Resemble.js#205]
Hi, my apologies if this is related to #195 

On the demo site, when comparing two images (I've tried both jpegs and pngs) with no overlap, it only states:
`"The second image is 20.44% different compared to the first."`
Whereas I would imagine it should be 100% different?

**Output:**
![output](https://user-images.githubusercontent.com/1598625/99145180-90a13080-2664-11eb-904e-64ac6302ad11.png)

**Input 1:**
![target](https://user-images.githubusercontent.com/1598625/99145186-9ac32f00-2664-11eb-8841-db41fcf690b8.png)

**Input 2:**
![user](https://user-images.githubusercontent.com/1598625/99145191-a44c9700-2664-11eb-9d04-dde4d5db72e5.png)

**Comment by jamescryer** [comment]
The pink pixels in the diff are 20.44% of the total diff image, even though the source images are literally 100% different.
