### ISSUE TITLE
Getting an error UnhandledPromiseRejectionWarning: TypeError: ImageData expected with images of different width

### ISSUE THREAD

**Issue by ua834** [rsmbl/Resemble.js#208]
When there is a diff and normalise function is being used I get this error. Happens with node v12.18.1 in Uubuntu 20.04.

packges:
    "@andreekeberg/imagedata": "^1.0.2",
    "pngjs": "^6.0.0",
    "resemblejs": "^3.2.5"

canvas version inside node_modules is "2.6.1"

my code:

`ar compare = async function(imgPath1, imgPath2){
  return new Promise(async (resolve, reject) => {
    const img1 = getSync(imgPath1);
    const img2 = getSync(imgPath2);

    resemble(img1)
    .compareTo(img2)
    // .scaleToSameSize()
    // .ignoreColors()
    .onComplete(function(data) {
        resolve(data);
    });
  })
}`

Images I've used for comparison:

![f1](https://user-images.githubusercontent.com/81559621/117801908-ace3eb80-b209-11eb-8832-bd52bbff67a3.png)
![f2](https://user-images.githubusercontent.com/81559621/117801918-af464580-b209-11eb-84f5-f62f5c2c8619.png)

**Comment by jamescryer** [comment]
It not clear what the error is.  Worth updgrading to the latest Resenble which uses Canvas@2.8.0
