### ISSUE TITLE
Can I remove nodejs support and redistribute this library?

### ISSUE THREAD

**Issue by ChenLuoi** [rsmbl/Resemble.js#211]
I only use resemblejs in browser, it's terrible to import the node-canvas dependency for me.
sometimes it would cause failure when run "npm i".
So, could I fork the repo, remove the nodejs support and redistribute it?

**Comment by jamescryer** [comment]
Try `npm i --no-optional`.

Resemble.js it MIT licenced so feel free to fork, modify and share, I only ask that you reference the original, and keep the same licence and copyright.
