### ISSUE TITLE
Compare from Image URL?

### ISSUE THREAD

**Issue by pietsteph** [rsmbl/Resemble.js#212]
Is it possible to compare 2 images from URL?

**Comment by Ephellon** [comment]
`I am not a maintainer on the project, just answering the question`

Yes, __if__ it is one of the following:

1) An image URL that can be loaded to the page (think CORS) &rarr; `https://github.githubassets.com/favicons/favicon.png`
2) A valid data URI &rarr; `data:image/png;base64,iVBORw0KGgo...`
