### ISSUE TITLE
Getting [object Event] error on complete

### ISSUE THREAD

**Issue by bpisano** [rsmbl/Resemble.js#214]
Hi everyone, I'm getting a strange error with resemble. It sometimes, for a reason I can't understand, return a `[object Event]` error on complete.

On the console, the error looks like this:
<img width="275" alt="Capture d’écran 2021-12-24 à 17 56 24" src="https://user-images.githubusercontent.com/16155946/147365926-61bef2e7-ef7c-4e57-a9e7-dede89d7cf82.png">

And here is the code I'm using to compare 2 `HTMLImageElement`:
```ts
public compareImages(img1: HTMLImageElement, img2: HTMLImageElement): Observable<number> {
  const url1: string = this.createUrlFromImage(img1);
  const url2: string = this.createUrlFromImage(img2);
  return new Observable((observer) => {
    resemble(url1)
      .compareTo(url2)
      .scaleToSameSize()
      .ignoreColors()
      .onComplete((data) => {
        console.log(data);
        observer.next(parseFloat(data.misMatchPercentage));
        observer.complete();
      });
  });
}
```

My images are valid and already at the same size. Both `url1` and `url2` are valid and can be displayed inside a `<img />` tag. I'm having troubles to identify when the error shows up. It seems completely random to me.

I'm performing the operation between twice and five times per second and I was wondering if it was not some kind of memory issue or something. The fact that the error `[object Event]` is a string value in the error leads me to think that this could be an issue with the library. But I can be wrong of course.

I'm using resemble on version `4.0.0`.

Thanks in advance for your help.

**Comment by jamescryer** [comment]
If you take out the Observer does it work? Perhaps its because Resemble keeps some shared/global state, it's best to implement multiple runs sequentially, or run in parallel on different processes or threads. 

At the very least it looks like there is a problem in the way Resemble is handling the error.

**Comment by bpisano** [comment]
Thanks for your reply. I tried to isolate the issue with a sample project to see if it is related with the Observable. For this example, I'm using React in a very simple way. The images I'm using are still valid and can be displayed in a `<img />` tag.

## Using Javascript `setInterval`
### Code
```tsx
type Nullable<T> = T | null;

function App() {
  const baseRef: any = useRef();
  const comparisonRef: any = useRef();

  useEffect(() => {
    compareWithInterval();
  }, []);

  function compareWithInterval() {
    setInterval(() => {
      compareImages();
    }, 1);
  }

  function compareImages() {
    const baseUrl: string = urlFromImage(baseRef.current);
    const comparisonUrl: string = urlFromImage(comparisonRef.current);
    resemble(baseUrl)
      .compareTo(comparisonUrl)
      .scaleToSameSize()
      .ignoreColors()
      .onComplete((data) => console.log(data));
  }

  // Utility function to convert images to url.
  function urlFromImage(image: HTMLImageElement): string {
    const canvas: HTMLCanvasElement = document.createElement("canvas");
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx: Nullable<CanvasRenderingContext2D> = canvas.getContext("2d");
    ctx?.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  }

  return (
    <div>
      <img src="/base.png" alt="" ref={baseRef} />
      <img src="/comparison.png" alt="" ref={comparisonRef} />
    </div>
  );
}
```
### Output
The first call leads to the `[object Event]` error. But the other calls to resemble are ok and a valid data is printed in the console:
<img width="541" alt="Capture d’écran 2022-01-03 à 12 02 53" src="https://user-images.githubusercontent.com/16155946/147923901-03a044fa-15c6-4b13-85f1-72ee97cbbc8a.png">

## Using RxJS asynchronously
### Code
```tsx
type Nullable<T> = T | null;

function App() {
  const baseRef: any = useRef();
  const comparisonRef: any = useRef();

  useEffect(() => {
    compareWithRxjsAsynchronously();
  }, []);

  function compareWithRxjsAsynchronously() {
    interval(1)
      .pipe(
        mergeMap(() =>
          // Compare 8 times in parallel.
          forkJoin(
            Array(8)
              .fill(0)
              .map(() => compareImagesObservable())
          )
        ),
        tap((dataArray) => dataArray.forEach((data) => console.log(data)))
      )
      .subscribe();
  }

  function compareImagesObservable(): Observable<resemble.ResembleComparisonResult> {
    const baseUrl: string = urlFromImage(baseRef.current);
    const comparisonUrl: string = urlFromImage(comparisonRef.current);
    return new Observable((observer) => {
      resemble(baseUrl)
        .compareTo(comparisonUrl)
        .scaleToSameSize()
        .ignoreColors()
        .onComplete((data) => {
          observer.next(data);
          observer.complete();
        });
    });
  }

  // Utility function to convert images to url.
  function urlFromImage(image: HTMLImageElement): string {
    const canvas: HTMLCanvasElement = document.createElement("canvas");
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx: Nullable<CanvasRenderingContext2D> = canvas.getContext("2d");
    ctx?.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  }

  return (
    <div>
      <img src="/base.png" alt="" ref={baseRef} />
      <img src="/comparison.png" alt="" ref={comparisonRef} />
    </div>
  );
}
```

### Output
The first 8 comparisons leads to the `[object Event]` error. But all other comparison returns a valid data that can be printed in the console:
<img width="541" alt="Capture d’écran 2022-01-03 à 12 10 03" src="https://user-images.githubusercontent.com/16155946/147924127-578d448c-9e29-44c4-bf45-1d549fae5182.png">

## Using RxJS synchronously
### Code
```tsx
type Nullable<T> = T | null;

function App() {
  const baseRef: any = useRef();
  const comparisonRef: any = useRef();

  useEffect(() => {
    compareWithRxjsSynchronously();
  }, []);

  function compareWithRxjsSynchronously() {
    interval(1)
      .pipe(
        concatMap(() =>
          // Compare 8 times sequentially.
          concat(
            Array(8)
              .fill(0)
              .map(() => compareImagesObservable())
          )
        ),
        tap((dataArray) => dataArray.forEach((data) => console.log(data)))
      )
      .subscribe();
  }

  function compareImagesObservable(): Observable<resemble.ResembleComparisonResult> {
    const baseUrl: string = urlFromImage(baseRef.current);
    const comparisonUrl: string = urlFromImage(comparisonRef.current);
    return new Observable((observer) => {
      resemble(baseUrl)
        .compareTo(comparisonUrl)
        .scaleToSameSize()
        .ignoreColors()
        .onComplete((data) => {
          observer.next(data);
          observer.complete();
        });
    });
  }

  // Utility function to convert images to url.
  function urlFromImage(image: HTMLImageElement): string {
    const canvas: HTMLCanvasElement = document.createElement("canvas");
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx: Nullable<CanvasRenderingContext2D> = canvas.getContext("2d");
    ctx?.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  }

  return (
    <div>
      <img src="/base.png" alt="" ref={baseRef} />
      <img src="/comparison.png" alt="" ref={comparisonRef} />
    </div>
  );
}
```

### Output
Same as using RxJS asynchronously. The first 8 comparisons leads to the `[object Event]` error. But the other ones are valid:
<img width="542" alt="Capture d’écran 2022-01-03 à 12 14 25" src="https://user-images.githubusercontent.com/16155946/147924470-2bbc0a71-7cfa-4914-aa63-e1240c4d4caf.png">

My guess is that it is not related to RxJS.

---

I tried to identify where the error could come from in your library. On the `resemble.js` file, in the `compare` function, it seems that this is near line 807 that you assign the `error` property to the `data`. I identified this piece of code:
```js
if (images[0].error || images[1].error) {
    data = {};
    console.log(images)
    data.error = images[0].error ? images[0].error : images[1].error;
    triggerDataUpdate();
    return;
}
```
By placing a `console.log` to show the content of the images array, I saw that the error was indeed `[object Event]` as a string as I got in my project:
<img width="541" alt="Capture d’écran 2022-01-03 à 12 40 29" src="https://user-images.githubusercontent.com/16155946/147926553-5ae87dea-b0f3-4178-8297-61047b4dacf3.png">

So I decided to go deeper and found this code on the `loadImageData` function:
```js
hiddenImage.onerror = function (err) {
    hiddenImage.onload = null;
    hiddenImage.onerror = null; // fixes pollution between calls
    console.log(err)
    images.push({ error: err ? err + "" : "Image load error." });
    callback();
};
```
I put a `console.log` here to display the error, and this is what I got:
<img width="539" alt="Capture d’écran 2022-01-03 à 12 43 39" src="https://user-images.githubusercontent.com/16155946/147926921-fc99d1df-1656-4886-9a11-62bfde17eefa.png">

The error was an `Event` and could be related to the error I'm getting on my projects. I'm still getting troubles to understand what happen here. But I hope that my explanations could help you or someone to identify the issue.

**Comment by bpisano** [comment]
After a day spent on this, finally found what's wrong. On the first call, the image are valid, but not yet loaded. My images are put in the public folder of my app, witch implies an http request to get the image. So the url passed to resemble looked like this: `data:,` witch is not a valid image url.

Resemble seems not to handle well this issue. One of the solution I've tested would be to change the error handling on the `loadImageData` to the following:
```js
hiddenImage.onerror = function (event) {
    hiddenImage.onload = null;
    hiddenImage.onerror = null; // fixes pollution between calls
    if (event.path && event.path[0]) {
        images.push({ error: `Failed to load image: ${event.path[0].currentSrc}`})
    } else {
        images.push({ error: err ? `Failed to load image with error: ${event}` : "Failed to load image. Unknown error." });
    }
    callback();
};
```

The error object is no more converted to a string value because of the `err + ""` that leaded to the `"[object Event]"`. This way, the error displayed on the console would look like this:
<img width="541" alt="Capture d’écran 2022-01-04 à 11 32 19" src="https://user-images.githubusercontent.com/16155946/148046230-3c32a81b-88e0-4a0f-9edb-9dc5fb2bc856.png">

This feels a bit more descriptive to me. What do you think?

**Comment by jamescryer** [comment]
Seems reasonable to me, would be happy to review a PR with this change.

**Comment by bpisano** [comment]
I just created #216. Don't hesitate to tell me if something is wrong.
